version: "3"
services:
  
  your-moon-server:
    build:
      context: server/
    image: your-moon-server
    container_name: your-moon-server
    restart: unless-stopped
    volumes:
      - "./data/server/config:/src/config"
      - "./data/server/uploadedImages:/src/uploadedImages"
      - "./data/server:/src/data"
  
  your-moon-redis:
    build:
      context: redis/
      dockerfile: Dockerfile
      args:
        REDIS_CONFIG: ${REDIS_CONFIG}
    image: your-moon-redis
    container_name: your-moon-redis
    restart: unless-stopped
  
  your-moon-client:
    build:
      context: client/
      args:
        BACKEND_URL: ""
        CONTACT_EMAIL: ${CONTACT_EMAIL}
    image: your-moon-client
    container_name: your-moon-client
    restart: unless-stopped
  
  your-moon-nginx:
    image: nginx:alpine
    container_name: your-moon-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    depends_on:
      - your-moon-server
      - your-moon-client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf